name: Front-end quality check

inputs:
  working-directory:
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ cat ${inputs.working-directory}./nvmrc }}
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Check for build errors
      run: npm run build:check
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run tests
      run: npm run test
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run linter and fix
      run: npm run lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run formatter and fix
      run: npm run format
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Check for remaining linter errors
      run: npm run lint:check
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Check for remaining formatting errors
      run: npm run format:check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
